"""Wire protocol for the Clawdia group-chat relay."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field


@dataclass
class RelayMessage:
    """Single protocol unit exchanged between relay server and clients.

    All datetimes travel as ISO 8601 UTC strings so no timezone info is lost
    over the wire, and JavaScript clients can parse them natively.

    ``seq`` is assigned by the server when a message is stored/broadcast;
    clients should treat the field as 0 (unset) until echoed back.
    ``message_id`` is generated by the sender and used for idempotent
    deduplication — re-sends of the same message carry the same UUID.
    """

    type: str  # "message" | "join" | "leave" | "presence" | "heartbeat" | "sync_request" | "sync_response" | "room_mode" | "typing" | "read" | "error"
    room_id: str
    sender_id: str
    sender_name: str
    sender_type: str  # "human" | "claude"
    timestamp: str  # ISO 8601 UTC, e.g. "2026-03-15T12:00:00.000000+00:00"

    seq: int = 0
    content: str | None = None
    reply_to_seq: int | None = None
    message_id: str = ""
    participants: list[dict] | None = None  # populated in presence updates
    error: str | None = None
    target_message_id: str | None = None  # for edit/delete targeting
    read_up_to_seq: int | None = None  # for read receipts

    # ------------------------------------------------------------------ #
    # Serialisation                                                        #
    # ------------------------------------------------------------------ #

    def to_json(self) -> str:
        """Serialise to a compact JSON string suitable for the wire."""
        # asdict produces a plain dict; drop keys whose value is None to keep
        # payloads small, but always include seq and message_id.
        raw = asdict(self)
        return json.dumps({k: v for k, v in raw.items() if v is not None or k in ("seq", "message_id")})

    @classmethod
    def from_json(cls, data: str | bytes) -> "RelayMessage":
        """Deserialise from a JSON string or bytes received over the wire."""
        payload = json.loads(data)
        # Accept any extra keys silently so older clients tolerate new fields.
        known_fields = cls.__dataclass_fields__  # type: ignore[attr-defined]
        filtered = {k: v for k, v in payload.items() if k in known_fields}
        return cls(**filtered)
